---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: 透過驗證對您的環境、網路存取、登入和 Web 瀏覽器的支持，開始使用NetApp勒索軟體復原能力。 
---
= NetApp勒索軟體復原能力前提條件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
透過驗證您的操作環境、登入、網路存取和 Web 瀏覽器的準備情況，開始使用NetApp勒索軟體復原能力。

要使用勒索軟體復原能力，您需要滿足以下先決條件。



== 在NetApp控制台中

* 具有組織管理員權限的NetApp控制台使用者帳戶，用於發現資源。
* 一個控制台組織，其中至少有一個活動的控制台代理連接到本地ONTAP叢集或 AWS 或 Azure 中的Cloud Volumes ONTAP 。
* 控制台代理必須具有 `cloudmanager-ransomware-protection`容器處於活動狀態。
* 至少一個具有NetApp本地ONTAP叢集或 AWS 或 Azure 中的Cloud Volumes ONTAP 的控制台系統。勒索軟體復原支援 NAS（NFS 和 SMB）和 SAN（iSCSI、FC 和 NVMe）協定。
+
** 支援具有ONTAP OS 版本 9.11.1 或更高版本的ONTAP或Cloud Volumes ONTAP叢集。
+

NOTE: 僅ONTAP 9.17.1 及更高版本支援 SAN 工作負載。

** 如果您的本機ONTAP叢集或 AWS 或 Azure 雲端中的Cloud Volumes ONTAP尚未在控制台中登錄，則需要控制台代理程式。
+
參考 https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["了解如何配置控制台代理"]和 https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["標準控制台要求"^]。

+

NOTE: 如果您在單一控制台組織中擁有多個控制台代理，則勒索軟體復原功能將掃描除控制台 UI 中目前選擇的代理之外的所有控制台代理中的ONTAP資源。







== 在ONTAP 9.11.1 及更高版本中

* 本機ONTAP實例上啟用了ONTAP One 授權。
* NetApp Autonomous Ransomware Protection 授權（由 Ransomware Resilience 使用）在本機ONTAP實例上啟用，視您使用的ONTAP版本而定。參考 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索軟體防護概述"^]。
+

NOTE: 與預覽版不同，Ransomware Resilience 的正式版包含NetApp Autonomous Ransomware Protection 技術的授權。參考 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索軟體防護概述"^]了解詳情。

+
有關更多許可詳細信息，請參閱link:concept-ransomware-resilience.html["了解勒索軟體抵禦能力"]。

* 若要套用保護配置（例如啟用自主勒索軟體保護等），勒索軟體復原能力需要ONTAP叢集上的管理員權限。  ONTAP叢集應該只使用ONTAP叢集管理員使用者憑證進行加入。
* 如果已使用非管理員使用者憑證在控制台中登入ONTAP集群，則必須透過登入ONTAP集群來更新非管理員使用者權限，如本頁所述。




== 用於資料備份

* NetApp StorageGRID、AWS S3、Azure Blob 或 Google Cloud Platform 中用於備份目標的帳戶以及設定的存取權。
+
請參閱 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS、Azure 或 S3 權限列表"^]了解詳情。

* 不需要在系統上啟用NetApp Backup and Recovery。
+
勒索軟體復原力有助於透過設定選項來配置備份目標。看link:rp-use-settings.html["配置設定"] 。





== 更新ONTAP系統中的非管理員使用者權限

如果您需要更新特定係統的非管理員使用者權限，請完成以下步驟。

. 登入控制台並尋找需要更新其ONTAP使用者權限的系統。
. 選擇系統以查看詳細資訊。
. 選擇“查看其他資訊”以顯示使用者名稱。
. 使用管理員使用者登入ONTAP集群 CLI。
. 顯示該使用者的現有角色。進入：
+
[listing]
----
security login show -user-or-group-name <username>
----
. 更改使用者的角色。進入：
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. 返回勒索軟體恢復 UI 來使用它。

