---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: 若要使用勒索軟體復原能力，請執行幾個步驟進行設定。 
---
= 設定NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
透過準備備份目的地、審查先決條件以及設定 NetApp Console 和 Console 代理程式，來設定 NetApp Ransomware Resilience。



[[prepare-the-backup-destination]]
== 準備備份目標

準備以下備份目標之一：

* NetAppStorageGRID
* 亞馬遜網路服務
* 谷歌雲端平台
* 微軟 Azure


在備份目的地本身設定選項後，稍後您需要將其設定為 Ransomware Resilience 中的備份目的地。有關如何在 Ransomware Resilience 中設定備份目的地的詳細資訊，請參閱 link:task-backup-destination.html["配置備份目標"]。



[[prepare-storagegrid-to-become-a-backup-destination]]
=== 準備StorageGRID以成為備份目標

如果要使用StorageGRID作為備份目標，請參閱 https://docs.netapp.com/us-en/storagegrid-117/index.html["StorageGRID文檔"^]有關StorageGRID的詳細資訊。



[[prepare-aws-to-become-a-backup-destination]]
=== 準備 AWS 成為備份目標

* 在 AWS 中設定一個帳戶。
* 配置 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS 權限"^]在 AWS 中。


有關在控制台中管理 AWS 存儲的詳細信息，請參閱 https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["管理您的 Amazon S3 儲存桶"^]。



[[prepare-azure-to-become-a-backup-destination]]
=== 準備 Azure 以成為備份目標

* 在 Azure 中設定一個帳戶。
* 配置 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Azure 權限"^]在 Azure 中。


有關在控制台中管理 Azure 儲存體的詳細信息，請參閱 https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["管理 Azure 儲存體帳戶"^]。



[[set-up-the-netapp-console]]
== 設定NetApp Console

下一步是設定 NetApp Console 和 Ransomware Resilience。

審查 https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["標準模式的控制台要求"^]。



[[create-a-console-agent]]
=== 建立控制台代理

請聯絡您的 NetApp 銷售代表以試用或使用此服務。然後 Console 代理程式將包含 Ransomware Resilience 所需的功能。

若要為 Ransomware Resilience 建立 Console 代理程式，請聯絡您的 Console 組織管理員（該管理員具有建立 Console 代理程式的權限），並參考 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["如何建立控制台代理"^]。


NOTE: 如果您有多個 Console 代理程式，Ransomware Resilience 會掃描所有 Console 代理程式的資料，而不僅僅是目前 Console 中顯示的代理程式。本服務會掃描與組織關聯的所有專案和 Console 代理程式的資料。
