---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: 尋找有關NetApp Ransomware Resilience的常見問題的答案。 
---
= 關於NetApp Ransomware Resilience的常見問題解答
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
如果您只是想快速找到有關NetApp Ransomware Resilience的問題的答案，那麼這個常見問題解答可以提供協助。



== 部署

.使用勒索軟體恢復功能需要許可證嗎？
您可以使用以下許可證類型：

* 註冊 30 天免費試用。
* 透過 Amazon Web Services (AWS) Marketplace、Google Cloud Marketplace 和 Microsoft Azure Marketplace 購買NetApp Intelligent Services和勒索軟體復原的即用即付 (PAYGO) 訂閱。
* 自帶授權 (BYOL)，即您從NetApp銷售代表取得的NetApp授權文件 (NLF)。您可以使用許可證序號在控制台的「Licenses and subscriptions」部分啟動 BYOL。


.如何啟用勒索軟體防禦能力？
您可以從NetApp Console存取勒索軟體復原功能。請確保您已 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["訪問角色"] 和 link:rp-start-prerequisites.html["先決條件"]。如果您已成功設定控制台代理，則可以執行下列操作： link:rp-start-discover.html["發現工作負載"]。

有關詳細信息，請參閱link:rp-start-login.html["存取勒索軟體彈性"]和link:rp-start-quick-start.html["勒索軟體抵禦能力快速入門指南"]。

.勒索軟體防護是否提供標準模式、限制模式和私有模式？
勒索軟體恢復功能目前僅在標準模式下可用。

有關所有NetApp資料服務中這些模式的說明，請參閱 https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["NetApp Console部署模式"^]。



== 使用權

.勒索軟體復原能力網址是什麼？
在瀏覽器中輸入 https://console.netapp.com/["https://console.netapp.com/ransomware-resilience"^] 訪問控制台。

.存取權限是如何管理的？
https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["了解所有服務的控制台存取角色"^]。勒索軟體復原能力也具備 link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-ransomware-roles.html["專用存取角色"^]。

.哪種設備解析度最佳？
勒索軟體恢復的建議設備解析度為 1920x1080 或更高。

.我該使用哪個瀏覽器？
您可以使用任何現代網頁瀏覽器存取NetApp Console。



== 互通性

.Ransomware Resilience 是否了解ONTAP中的保護設定？
是的，Ransomware Resilience 發現了在ONTAP中設定的快照計劃。

.勒索軟體復原功能如何與NetApp Backup and Recovery和SnapCenter互動？
勒索軟體復原功能與備份和復原功能協同工作，以發現並設定檔案共享工作負載的快照和備份策略。

Ransomware Resilience 可與 SnapCenter 或 SnapCenter for VMware 搭配使用，以發現並設定應用程式和虛擬機器工作負載的快照和備份策略。目前，您無法將 Ransomware Resilience 與 SnapCenter 搭配使用進行復原。

NetApp Ransomware Resilience 也可與 NetApp Backup and Recovery 搭配使用，以執行檔案和工作負載一致的還原。

對於許可和計費，即使您沒有單獨的備份和復原許可證，勒索軟體復原功能也可以與備份和復原功能整合。如果您同時擁有備份和復原以及勒索軟體復原功能，則受這兩種產品保護的任何公開資料僅由勒索軟體復原功能計費。



== 工作負載

.在勒索軟體防禦的脈絡下，什麼是工作負載？
工作負載是一個應用程式、一個虛擬機器或一個檔案共用。工作負載包括單一應用程式執行個體所使用的所有磁碟區。

例如，考慮部署在 ora3.host.com 上的 Oracle 資料庫。 `vol1` 包含數據和 `vol2` 包含日誌。這兩個磁碟區構成了該 Oracle 資料庫執行個體的工作負載。

.勒索軟體復原能力如何決定工作負載資料的優先順序？
工作負載優先順序（關鍵、標準、重要）由已應用於與工作負載關聯的每個磁碟區的快照頻率和排程備份決定。

link:rp-use-protect.html["了解工作負載優先順序或重要性"] 。

.勒索軟體復原能力支援哪些工作負載？
勒索軟體復原能力可以識別以下工作負載：Oracle、檔案共享、區塊儲存、虛擬機器和虛擬機器資料儲存。

如果您正在使用 SnapCenter 或 SnapCenter for VMware，則這些產品支援的所有工作負載也會在 Ransomware Resilience 中被識別。

.如何將資料與工作負載關聯？
勒索軟體復原能力會發現捲和檔案副檔名，並將它們與相應的工作負載關聯起來。

如果您擁有SnapCenter或SnapCenter for VMware，並且在備份和復原中配置了工作負載，那麼勒索軟體復原功能將發現由SnapCenter和SnapCenter for VMware 管理的工作負載及其關聯的磁碟區。

.什麼是受保護的工作負載？
在勒索軟體復原能力中，當工作負載啟用了主要偵測策略時，其狀態將顯示為“*受保護*”，這意味著 link:concept-ransomware-resilience.html["自主勒索軟體防護 (ARP)"] 已在與工作負載相關的所有磁碟區上啟用。

.什麼是「高風險」工作量？
如果工作負載未啟用主偵測策略，即使啟用了備份和快照策略，也會被標記為「有風險」。為了防止勒索軟體攻擊，您應該啟用… link:rp-use-protect.html#add-a-ransomware-protection-strategy["檢測策略"]。

.我新增了一個新卷，但它還沒有顯示出來。我該怎麼辦？
如果您在環境中新增了新磁碟區，請重新啟動工作負載發現。在發現體積後， link:rp-use-protect.html#add-a-ransomware-protection-strategy["採取保護策略以保護新增容量"]。



== 保護策略

.勒索軟體復原策略是否可以與其他類型的工作負載策略共存？
目前，備份和復原（雲端備份）支援每個磁碟區一個備份策略。如果您使用備份和復原功能來設定備份保護，它將與勒索軟體復原功能共用備份策略。

快照副本不受限制，可以從每個服務單獨新增。

.勒索軟體防護策略需要哪些策略？
一個 link:rp-use-protect.html#add-a-ransomware-protection-strategy["勒索軟體防護策略"] 需要：

* 勒索軟體偵測策略，以及
* 快照策略


勒索軟體抵禦策略中不需要備份策略。

.Ransomware Resilience 是否了解ONTAP中的保護設定？
是的，Ransomware Resilience 可以發現 ONTAP 中設定的快照排程。它還可以發現已發現工作負載中的所有磁碟區是否都啟用了 ARP 和 FPolicy。您在 Ransomware Resilience 儀表板中看到的資訊是從其他 NetApp 解決方案和產品彙總而來。

.勒索軟體復原功能是否了解備份和復原以及SnapCenter中已製定的策略？
是的，如果您在備份和復原或SnapCenter中管理工作負載，則這些產品管理的策略將納入勒索軟體復原能力。

.能否修改從NetApp Backup and Recovery和/或SnapCenter繼承的策略？
不可以，您無法從 Ransomware Resilience 修改由備份和還原或SnapCenter管理的政策。您可以在「備份和復原」或SnapCenter中管理對這些政策的任何變更。

.如果ONTAP中存在政策（例如 ARP、FPolicy 和快照），這些策略是否會在勒索軟體復原功能中變更？
不會。勒索軟體復原不會修改ONTAP中的任何現有偵測策略（ARP、FPolicy 設定）。

.註冊勒索軟體復原功能後，如果在備份和復原或SnapCenter中新增政策會發生什麼情況？
勒索軟體復原能力可以識別備份和復原或SnapCenter中新建立的策略和原則變更。

.能否透過ONTAP更改策略？
是的，您可以在 Ransomware Resilience 中從ONTAP更改策略。您也可以在勒索軟體復原中建立新策略並將其應用於工作負載。此操作將以在勒索軟體復原中建立的策略取代現有的ONTAP策略。

.可以在ONTAP中停用策略嗎？
您可以使用ONTAP中的系統管理員 UI、API 或 CLI 在偵測策略中停用 ARP。

您可以透過套用不包含 FPolicy 和備份策略的其他策略來停用它們。
