---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: 透過驗證對您的環境、網路存取、登入和 Web 瀏覽器的支持，開始使用NetApp Ransomware Resilience。 
---
= NetApp Ransomware Resilience前提條件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
為確保 NetApp Ransomware Resilience 的成功部署，請驗證您的操作環境、網路存取和網路瀏覽器是否已準備就緒。

請檢查並確保您符合以下要求。



== 支援的系統

請確保您使用的是受支援的系統：

|===
| 環境 | 協定 | 支援的版本 


| Amazon FSx for NetApp ONTAP* | CIFS、NFS 和 SAN | 不適用 


| Azure NetApp Files | CIFS 和 NFS | 不適用 


.2+| 適用於 AWS 的Cloud Volumes ONTAP | CIFS 和 NFS | 9.11.1 及更高版本 


| SAN（iSCSI 和 NVMe） | 9.17.1 及更高版本 


.2+| 適用於 Google Cloud Platform 的Cloud Volumes ONTAP | CIFS 和 NFS | 9.11.1 及更高版本 


| SAN（iSCSI 和 NVMe） | 9.17.1 及更高版本 


.2+| 適用於 Microsoft Azure 的Cloud Volumes ONTAP | CIFS 和 NFS | 9.12.1 及更高版本 


| SAN（iSCSI 和 NVMe） | 9.17.1 及更高版本 


.2+| ONTAP （本地部署） | CIFS 和 NFS | 9.11.1 及更高版本 


| SAN（FC、iSCSI 和 NVMe） | 9.17.1 及更高版本 
|===
{asterisk} Amazon FSx for NetApp ONTAP使用自主勒索軟體保護 (ARP) 而非 ARP/AI。有關兩者區別的更多信息，請參閱link:https://docs.netapp.com/us-en/ontap/anti-ransomware/#arp-ai["ARP/AI"^]。



== NetApp Console需求

您的NetApp Console配置需要：

* 具有組織管理員權限的NetApp Console使用者帳戶，用於發現資源。
* 一個控制台組織和系統，其中至少有一個活動的控制台代理連接到link:concept-ransomware-resilience.html#supported-backup-targets-systems-and-workload-data-sources["支援的系統"]。
+
** 如果您的內部部署 ONTAP 叢集或 Cloud Volumes ONTAP 系統未在 Console 中設定，請參閱 link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["了解如何配置控制台代理"^] 和 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["標準控制台要求"^]。
+

NOTE: 如果您在單一控制台組織中擁有多個控制台代理，則勒索軟體復原功能將掃描除控制台 UI 中目前選擇的代理之外的所有控制台代理中的ONTAP資源。



* 控制台代理必須具有 `cloudmanager-ransomware-protection`容器處於活動狀態。
* 對於 ONTAP 或 Cloud Volumes ONTAP 叢集，Ransomware Resilience 要求 ONTAP 版本為 9.11.1 或更高版本。
+

NOTE: 若要在 SAN 工作負載上使用勒索軟體復原功能，您必須執行ONTAP 9.17.1 或更高版本。





== ONTAP 需求

* 您必須執行ONTAP 9.11.1 或更高版本，並且在本機ONTAP實例上啟用ONTAP One 授權。有關ONTAP支援的更多信息，請參閱link:https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自主勒索軟體防護概述"^]。
* 若要套用保護配置（例如啟用自主勒索軟體保護），勒索軟體復原能力需要ONTAP叢集上的管理員權限。ONTAP叢集應該只使用ONTAP叢集管理員使用者憑證進行加入。



NOTE: 如果您已使用非管理員憑證將ONTAP叢集連接到控制台，則[您必須更新ONTAP叢集中的憑證](#update-non-admin-user-permissions-in-an-ontap-system)。



== 資料備份

* 在NetApp StorageGRID、AWS S3、Azure Blob 或 Google Cloud Platform 中擁有一個帳戶，用於備份目標，並配置了適當的存取權。
+
請參閱 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS、Azure 或 S3 權限列表"^]了解詳情。

* 不需要在系統上啟用NetApp Backup and Recovery 。
+
Ransomware Resilience 可透過「設定」選項配置備份目標位置。請參閱 link:task-backup-destination.html["新增備份目標"]。





== 可疑用戶行為要求

為了使 Ransomware Resilience 能夠發出有關可疑使用者行為的警報，您必須設定使用者活動代理程式。若要安裝使用者活動代理程式，請確保您的系統符合link:reference-user-activity-requirements.html["要求"]。



== 更新ONTAP系統中的非管理員使用者權限

如果您需要更新特定系統中的非管理員使用者權限，請依照下列步驟操作。

. 登入 Console 。在儀表板中，找到需要更新 ONTAP 使用者權限的系統。
. 選擇系統以檢視其詳細資訊。
. 選擇“查看其他資訊”以顯示使用者名稱。
. 以管理員使用者身分登入ONTAP集群 CLI。
. 顯示該使用者的現有角色：
+
[listing]
----
security login show -user-or-group-name <username>
----
. 更改使用者的角色。進入：
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. 返回NetApp Console以使用勒索軟體復原功能。

