---
sidebar: sidebar 
permalink: task-users-manage.html 
keywords: user activity detection, 
summary: 在 NetApp Ransomware Resilience 中建立使用者目錄連接器後，您可以封鎖和解除封鎖使用者，並將使用者從警示清單中排除。您也可以將檔案路徑排除在警示產生範圍之外。 
---
= 在 NetApp Ransomware Resilience 中管理警示與封鎖的使用者
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在 NetApp Ransomware Resilience 中設定使用者行為監控後，您可以自訂警報並管理被封鎖的使用者。自訂警報可讓您將特定使用者或檔案路徑排除在警報產生範圍之外。封鎖使用者旨在回應勒索軟體事件，以防止惡意使用者活動。

您必須link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#create-a-user-activity-agent["配置了使用者活動代理，啟用了具有使用者活動偵測功能的原則，並建立了使用者目錄連接器。"]才能封鎖使用者。


TIP: 您可以link:task-automate-user-activity.html["自動回應"]查看使用者活動偵測事件。



[[manage-blocked-users]]
== 管理已封鎖用戶

如果您認為某個使用者從事惡意活動，您可以將其封鎖。

.封鎖用戶
. 在勒索軟體恢復功能中，選擇**設定**。
. 在「設定」儀表板中，找到「使用者活動監控」磁貼，然後選擇 **Manage**。
. 選取「使用者」索引標籤。
. 選取**封鎖使用者**。
. 選擇封鎖持續時間：可以是 1 小時到 24 小時，也可以是永久封鎖。
. 選取要封鎖的使用者名稱旁的核取方塊。
. 選擇 **Block**。


.修改已封鎖使用者列表
. 在勒索軟體恢復功能中，選擇**設定**。
. 在「設定」儀表板中，找到「使用者活動監控」磁貼，然後選擇 **Manage**。
. 選取「使用者」索引標籤。
. 選擇**編輯使用者屏蔽**。
. 選擇修改選項。若要修改封鎖時長，請選擇 **封鎖使用者的時間段**，然後修改時長。若要從封鎖使用者清單中移除使用者，請選擇 **解除封鎖使用者**。
. 選取要變更狀態的被封鎖使用者名稱旁的核取方塊。
. 選擇**儲存**。




[[exclude-users-from-alerts]]
== 將使用者排除在警示範圍之外

如果某些受信任使用者的行為可能會觸發使用者行為警示，您可以將他們從警示中排除。

.將使用者排除在警示範圍之外
. 在勒索軟體恢復功能中，選擇**設定**。
. 在「設定」儀表板中，找到「使用者活動監控」磁貼，然後選擇 **Manage**。
. 選取「**排除在監控之外**」索引標籤。
. 若要在使用者介面中檢閱個別使用者，請選擇 **手動選取**。若要上傳排除的使用者清單，請選取 **上傳**。
+
.. 如果您選擇了 **Select manually**，請選取要排除的特定使用者名稱旁的核取方塊。
.. 如果您選擇 **Upload**，請下載包含所有使用者清單的 CSV 或 JSON 檔案。選擇 **Download** 即可存取該清單。
+
在本機上，查看該檔案。刪除所有您希望保留偵測的使用者名稱。當清單中僅包含您希望從偵測中排除的使用者名稱時，請儲存該檔案。

+
在 Ransomware Resilience 中，選取 **Upload**。找到並上傳檔案。



. 選擇**新增**以完成將使用者新增至排除清單的操作。
. 在「**已排除在監控之外**」標籤中，現在會在儀表板中顯示已從使用者行為偵測警示中移除的使用者名稱。



TIP: 您也可以直接將使用者從警示中排除。如需詳細資訊、請參閱 link:rp-use-alert.html["回應勒索軟體警示"]。

.從排除使用者清單中移除使用者
. 在「設定」儀表板中，找到「使用者活動」卡片，然後選取 **Manage**。
. 選取「**排除在監控之外**」索引標籤。
. 選擇**新增**。
. 若要從使用者介面中排除個別使用者，請選擇 **手動選擇**。
. 從排除使用者清單中找到要移除的使用者名稱。選取使用者名稱所在列上的動作選單 (`...`，然後選取 **Remove**。
. 在對話方塊中、選取 **Remove** 以確認您要移除所選使用者。




[[exclude-file-paths-from-monitoring]]
== 從監控中排除檔案路徑

每個檔案路徑必須以磁碟區名稱開頭。它可以包含該磁碟區最多三個子目錄，例如「volume/directory/subdirectory/subdirectory2」。您可以手動輸入檔案路徑或上傳包含路徑清單的 CSV 檔案來排除某些檔案路徑。

.步驟
. 在勒索軟體恢復功能中，選擇**設定**。
. 在「使用者活動監控」磁貼中，選擇 **Manage**。
. 選擇「*排除在監控之外*」標籤。
. 選擇**新增**以輸入要排除的檔案路徑。
. 若要在使用者介面中輸入檔案路徑，請選擇「手動輸入」單選按鈕，然後輸入檔案路徑，例如「volume/directory/subdirectory/」。若要輸入其他檔案路徑，請選擇**選擇檔案路徑**。
. 若要上傳檔案路徑列表，請選擇「上傳」單選按鈕。選擇上傳按鈕以選擇 CSV 檔案。
. 選擇**新增**。


.結果
操作成功完成後，Ransomware Resilience 會將選取路徑中的檔案從可疑使用者行為監控中排除。您可以隨時在「設定」選單中查看路徑清單。如果需要重新啟用對這些檔案路徑的監控，您可以將其從清單中移除。



[[next-steps]]
== 後續步驟

* link:task-automate-user-activity.html["自動回應使用者活動偵測事件"]

