= 來自Digital Advisor的安全風險評估
:allow-uri-read: 




[[security-risk-assessment-from-digital-advisor]]
=== 來自Digital Advisor的安全風險評估

BlueXP 勒索軟體保護現在從 NetApp Digital Advisor 收集有關高風險和關鍵叢集安全性風險的資訊。如果發現風險，BlueXP 勒索軟體保護會在儀表板的「建議動作」窗格中顯示以下建議：「修正叢集上的已知安全性漏洞 <name>。」從儀表板建議中，選取「審查並修復」即可審查 Digital Advisor 和相關的通用漏洞與揭露 （CVE） 文章。如果存在多個安全性風險，請在 Digital Advisor 中審查詳細資訊。

參考 https://docs.netapp.com/us-en/active-iq/index.html["Digital Advisor文檔"^]。



[[back-up-to-google-cloud-platform]]
=== 備份到 Google Cloud Platform

在此版本中，您可以將備份目標設定為 Google Cloud Platform 儲存桶。以前，您只能將備份目標新增至NetApp StorageGRID、Amazon Web Services 和 Microsoft Azure。

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-backup-destination.html["了解有關配置BlueXP ransomware protection設定的更多信息"].



[[support-for-google-cloud-platform]]
=== 支持 Google Cloud Platform

該服務現在支援適用於 Google Cloud Platform 的Cloud Volumes ONTAP進行儲存保護。先前，該服務僅支援適用於 Amazon Web Services 和 Microsoft Azure 的Cloud Volumes ONTAP以及本機 NAS。

https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["了解BlueXP ransomware protection以及支援的資料來源、備份目標和工作環境"] 。



[[role-based-access-control]]
=== 基於角色的存取控制

現在您可以使用基於角色的存取控制 (RBAC) 限制對特定活動的存取。  BlueXP ransomware protection使用BlueXP的兩個角色： BlueXP帳號管理員和非帳號管理員（檢視者）。

有關每個角色可以執行的操作的詳細信息，請參閱 https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["基於角色的存取控制權限"]。
