= 
:allow-uri-read: 


.無塵室 SVM 資料 LIF IP（crr-data-LIF-IP）
* 為潔淨室 SVM 資料 LIF 配置 IP 位址。記下該 IP 位址：IRE 組態程序中需要用到此 IP 位址。
+
** 對於使用雲端到雲端乾淨還原的 AWS Cloud Volumes ONTAP，請確保已將 IP 位址指派給彈性網路介面。


* 允許從 SVM 資料 LIF IP 路由到 IRE。



NOTE: 如果您正在為 ONTAP 配置來源為 Amazon FSxN 的 IRE，請跳過此無塵室 SVM 資料 LIF IP 要求。

.正式作業環境路由表
* 生產路由表必須允許來自 IRE 子網路到乾淨還原資料 LIF IP 的流量。您必須將此路由新增至生產路由表。
* 正式作業 ONTAP 叢集上的安全群組和防火牆應允許 NFSv4 和 NFSv3 傳入流量傳送至全新還原資料 LIF IP。防火牆應開放來自 IRE CIDR 範圍的傳入流量：
+
[cols="1,1,1,1"]
|===
| 協定 | 目的地連接埠 | 來源 | 目的 


| TCP 與 UDP | 2049 | IRE VPC CIDR 範圍 | 從 IRE 存取 NFSv4 


| TCP 與 UDP | 111 | IRE VPC CIDR 範圍 | 從 IRE 存取 NFSv3 


| TCP 與 UDP | 635 | IRE VPC CIDR 範圍 | 從 IRE 存取 NFSv3 


| TCP 與 UDP | 4045 | IRE VPC CIDR 範圍 | 從 IRE 存取 NFSv3 


| TCP 與 UDP | 4046 | IRE VPC CIDR 範圍 | 從 IRE 存取 NFSv3 


| TCP 與 UDP | 4049 | IRE VPC CIDR 範圍 | 從 IRE 存取 NFSv3 
|===


.IRE 路由表
* IRE 路由表應該是 IRE VPC 中的主路由表。
* IRE 路由表應允許路由到乾淨復原資料 LIF IP 位址。
* IRE 路由表也應允許通往公用網際網路的路由，以便 IRE 代理程式運作。


.虛擬私有雲（VPC）
* 對於 IRE，請在生產環境的 IP 位址範圍內佈建 VPC。IP 位址不應與任何現有的 IP 位址衝突。
+
** VPC 至少應有 64 個 IP 位址（/26 網路遮罩）。
** VPC 必須允許公用網際網路存取。否則、Console 代理程式將無法運作。




.雲端權限
* Ransomware Resilience 需要具備正確 IAM 權限的 AWS 存取金鑰和密碼金鑰，才能在 AWS 環境中執行全新還原。link:https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_create.html["在 AWS 中建立 IAM 原則"^]具備下列權限，然後將原則附加至新建立的使用者。建立使用者之後，請產生 IAM 認證資料並提供給全新還原。


[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EC2Isolated recovery environmentFullAccess",
            "Effect": "Allow",
            "Action": "ec2:*",
            "Resource": "*",
            "Condition": {
                "StringLike": {
                    "aws:ResourceTag/rps::Isolated recovery environment-name": "*"
                }
            }
        },
        {
            "Sid": "EC2CreateAccess",
            "Effect": "Allow",
            "Action": [
                "ec2:*"
            ],
            "Resource": "*"
        },
        {
            "Sid": "EC2ReadPermissions",
            "Effect": "Allow",
            "Action": [
                "ec2:Describe*"
            ],
            "Resource": "*"
        },
        {
            "Sid": "IAMFullAccess",
            "Effect": "Allow",
            "Action": "iam:*",
            "Resource": "*",
            "Condition": {
                "StringLike": {
                    "aws:ResourceTag/rps::Isolated recovery environment-name": "*"
                }
            }
        },
        {
            "Sid": "S3FullAccessToIsolated recovery environmentStateBucketCreation",
            "Effect": "Allow",
            "Action": [
                "s3:CreateBucket"
            ],
            "Resource": "*"
        },
        {
            "Sid": "S3FullAccessToIsolated recovery environmentStateBucketObjects",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::*-netapp-Isolated recovery environment-state-bucket/*"
        },
        {
            "Sid": "S3FullAccessToIsolated recovery environmentStateBucket",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::*-netapp-Isolated recovery environment-state-bucket"
        }
    ]
}
----